### ISSUE TITLE
[FR] "getting started" / "Quick Start Tour" section

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/dtdocs#209]
There has been talk at various times about improving the "onboarding" process for new dt users.  To help in this, the manual should have a section _right_ _at_ _the_ _beginning_ that takes a user through importing an image/folder, making some simple edits, and exporting the result.  While also pointing out powerful features such as presets, shortcuts, etc. with links to the appropriate sections of the manual.

This would also be a good place to link Bruce Williams' recent three-part "dt 3.4 for newbs" video.  New users will never find their way to the resources chapter in the back of the manual....

**Comment by paperdigits** [comment]
We have those tutorials pretty close to the front: https://darktable-org.github.io/dtdocs/overview/workflow/

**Comment by ralfbrown** [comment]
"Basic Workflow" doesn't scream read-me-if-you're-new-to-dt, especially since it's halfway down the sidebar nested inside another section.  Remember that for most people, RTFM is a last recourse when all else has failed....

Begin with the contents of that section, but move it to the very beginning and name it "quick start" or the like, so that new users can't miss it.  Also make it a step-by-step run-through (do A, then B, then C) rather than reference material.

It would be really cool if we could have a first-run splash screen in dt that linked to the quick start and/or some introductory videos (though the latter would be difficult to keep up-to-date).

**Comment by paperdigits** [comment]
Yes I have a to do to make the content step based. It already sort of is, it just isn't numbered.

**Comment by Akelbeee** [comment]
Hello! I'm a newbee with dt, for the time struggling to get to grips with all the basic niceties. (Made an initial attempt one year ago, but luckily got seriously ill within short time, since I now rather can work with the much improved manual and dt 3.4. Thanks for all good efforts that have brought us to where docs and dt stand now!) I belong to the kind of users who actually starts with the manual to learn the program.

For all the good things that can now be said about the newest version, for a newbee -- not only to dt, but to image processing in general -- the initial part of the manual,  the text/structure of ch. 1 - 3, smells a little too much of "engineer". It feels like being written by somebody who makes/knows the product, and hence is a little too much influenced by the structure/mechanisms of the underlying program, (I can exemplify that if needed), rather than meeting us who come with the questions "what kind of an animal is this?" and "how can I get it to do the acts I want without it biting me?". I believe we could improve the more general parts of the manual to better help ease newcomers into the fold. 

I have noted down all my reactions to (those parts I've so far read of) the documentation while I force my way forward -- from typos and inconsistent use of terms, suggestions for amended/additional text that may clarify, thoughts on restructuring of initial parts of the manual and to reflections that it's a tall order to require that we shall all have to join GitHub just for reporting some typos ... 

So, yes, I agree fully with the intent of this FR, and am motivated to contribute with my expert-perspective on a non-expert's challenges and needs. 

I'm a little unsure, though, as for how to best go on, and would appreciate, some guidance in this respect.
Cheers!
Espen

**Comment by paperdigits** [comment]
Hi @Akelbeee,

Thanks for the offer of contributions! For things like *typos and inconsistent use of terms, suggestions for amended/additional text that may clarify*, please issue github pull requests.

For things like *thoughts on restructuring of initial parts of the manual* please a separate issue and describe in detail what you'd like to change. I do this before doing any actual work changing the structure of things. As noted in our README file, expect to be met with some tough questions, as several of us have already taken a good bit of time to reason how the manual should be structured.

Thanks!

**Comment by Akelbeee** [comment]
Thanks @paperdigits , I will do.

I'll just first have to find out how GitHub works (e.g. how does a pull request work) and learn Markdown, and understand what's the smallest and largest chunk of info that should be addressed as one issue here in development of the manual - e.g. how much or little can/should be put into one pull request: one single typo in one paragraph or several at once? Will revert in a few days.

GitHub is just like dt - and any other application: All that's self evident for experienced users are unknown for novices. There's nearly no thing small enough to not make one stop up. And that's also why I believe that in the initial part of the dt manual there is something to gain from being somewhat more accommodating for those who have no background yet (-- that is, if one really want to get new users of dt, but several forum comments on pixls.us can cause a certain doubt in this respect ...).

**Comment by Akelbeee** [comment]
- and, @paperdigits , I don't find anything like what you indicate in the README file, just some technical stuff. (There's some "restrictive" statements on poilicy in the "contribute" chapter of the manual, though), I'm anyhow prepared for tough discussions.

**Comment by ralfbrown** [comment]
> (-- that is, if one really want to get new users of dt, but several forum comments on pixls.us can cause a certain doubt in this respect ...).

The pushback is not so much against new users in general, as against hordes of new users switching from some commercial program who then either complain that dt doesn't work *exactly* like their old program or (worse) demand that dt be changed to work that way, thereby wasting lots of the devs' time.  That's why suggestions that dt should implement X like the commercial program(s) to gain more users get looked at with skepticism.

**Comment by paperdigits** [comment]
> how much or little can/should be put into one pull request: one single typo in one paragraph or several at once

You can certainly put multiple typos in one pull request. It is easier for us to review and approve if your pull request is centered around one thing. If you want to pull all your typo fixes in one pull request that is fine. What we want to avoid is a pull request that had typos, attempts at clarification, and restructuring all in one pull request. 

> GitHub is just like dt - and any other application: All that's self evident for experienced users are unknown for novices. There's nearly no thing small enough to not make one stop up.

Sure there is always some gating factor, and some factors will gate some people. It wouldn't be any different if we used mediawiki and you didn't know how to use wikipedia, or if we wrote in Microsoft Word and you didn't know how to use that. 

> And that's also why I believe that in the initial part of the dt manual there is something to be gained from being somewhat more accommodating for those who have no background yet (-- that is, if one really want to get new users of dt, but several forum comments on pixls.us can cause a certain doubt in this respect ...).

Yes, we're open to ideas, but keep in mind that the manual isn't aimed solely at newbies. Its aim is right in the middle. Also the manual tells you how it works. Videos, other workflow tutorials, or a class with an instructor may serve you better in getting to grips with the "what to do in darktable" and similar questions. 

> I don't find anything like what you indicate in the README file, just some technical stuff.

Sorry, I forgot that we restructured things, so now that page is in the manual itself: https://darktable-org.github.io/dtdocs/special-topics/contributing/
