### ISSUE TITLE
channel mixing using colour calibration

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtdocs#214]
https://www.darktable.org/usermanual/en/module-reference/processing-modules/color-calibration/#channel-mixing

_The use of any of the CAT spaces can make the channel mixer tuning process easier, due to their connection with human physiology_
I think the use of adaptation spaces (and the differences from _red_, _green_ and _blue_) should be emphasised, especially given that the labels remain R, G and B even if using an adaptation space (e.g. XYZ).

_but it is also possible to mix channels in the RGB working space of the pipeline by setting the adaptation to “none (bypass)”_
The _channel mixer_ preset, and the different colour channel swaps that make it rather obvious what is happening, are worth a mention here.

_To perform channel mixing in one of the adaptation color spaces without chromatic adaptation, set the illuminant to “same as pipeline (D50)”._
I don't know when it is beneficial to use an adaptation space without adaptation; I'd be grateful for an explanation of the potential benefits and drawbacks.

**Comment by elstoc** [comment]
Ping @aurelienpierre.

**Comment by aurelienpierre** [comment]
> I think the use of adaptation spaces (and the differences from red, green and blue) should be emphasised, especially given that the labels remain R, G and B even if using an adaptation space (e.g. XYZ).

I have stopped caring about that RGB shit a long time ago. RGB is not RGB. XYZ is RGB. RGB is just some dumb way to say that we split a spectrum into 3 channels that look roughly red, green and blue, with no guaranty on the redness, greenness and blueness. 

As far as I'm concerned, it's a 3D space to write vectors. The rest is bullshit.

> I don't know when it is beneficial to use an adaptation space without adaptation; I'd be grateful for an explanation of the potential benefits and drawbacks.

Since RGB spaces suck in general, perceptually-speaking, you might as well use an RGB space that at least matches retina cone sensitivity, so the LMS Bradford/CAT16 spaces are the lesser evil.

**Comment by elstoc** [comment]
@kofa73 if you want to propose some wording in a PR I'm happy to consider it but I think the consensus here is that it's not worth changing.
