### ISSUE TITLE
small spelling error in parametric.md

### ISSUE THREAD

**Issue by diefau** [darktable-org/dtdocs#246]
In line 24 it should be 'representation' (instead of 'represrntation')

**Comment by paperdigits** [comment]
Good catch! Can you submit a pull request to fix it please?

**Comment by elstoc** [comment]
Don't worry - I'll do it now

**Comment by diefau** [comment]
Oh, I thought the po-file(s) will be created automatically. 
This doesn't seem so, because this typo is in po/content.pot, po/content.pt-br.po and po/content.fr-fr.po too.

And another thought: in the manual 'gray' and 'grey' are mixed up. I think i't should only be 'gray'?

**Comment by elstoc** [comment]
> in the manual 'gray' and 'grey' are mixed up

I think the same is true in darktable itself as well. It's the one word where I can never remember which is the British English and which the American English. But we're going for American English here (mainly because of the word "color" being spelled in the American way throughout darktable) so I guess gray is "correct". Where the darktable interface uses "grey" though, we should fix darktable first.

I've previously raised https://github.com/darktable-org/darktable/issues/6791 discussing these issues.

**Comment by elstoc** [comment]
I've raised https://github.com/darktable-org/darktable/pull/8554 to fix darktable interface. Once that's merged I'll look at updating dtdocs.

**Comment by elstoc** [comment]
Should now be "gray" throughout in both darktable and dtdocs (I think)

**Comment by paperdigits** [comment]
We have to generate the po and pot files.
