### ISSUE TITLE
Links to images do not work

### ISSUE THREAD

**Issue by lebmich** [darktable-org/dtdocs#249]
In the French translation no link to the images works.
For example, I get:
![2021_04_02_weblate_03](https://user-images.githubusercontent.com/33633321/113435593-6c5fa980-93e3-11eb-8bd6-f6301c05e8d8.png)

**Comment by paperdigits** [comment]
Did you translate the image path or image file name? That'll cause it not to work.

**Comment by lebmich** [comment]
I translated nothings at all.
The link to the image in my browser is: 
![2021_04_03_weblate_04](https://user-images.githubusercontent.com/33633321/113470818-a4550400-9458-11eb-8684-56d65843a101.png)

**Comment by paperdigits** [comment]
@elstoc I've been looking at this problem for a while, and I don't see the solution. Hopefully I'm missing something obvious.

Because of the decision we made about storing images in a folder with the same name as the file, we use `{{ .Page.RelPermalink }}`j + the image file name to construct the image URL for English text. But when we translate the page, `{{ .Page.RelPermalink }}` includes the translated locale, e.g. `fr-fr`, in the URL. 

I guess  the proper solution would be to check if there is a translated image, and if no, then fall back to the English URL.

Any ideas?

**Comment by elstoc** [comment]
Haven't we decided already that it's not possible to translate the images? If so, surely the render-image partial can check if the page is non-English using `.Page.Language` and then if not, loop through `.Page.Translations` until it finds the English version (with `.Lang`), then use the `.RelPermaLink` to build the link for that one.

**Comment by paperdigits** [comment]
> Haven't we decided already that it's not possible to translate the images?

Yes, I believe so.

This is a good thread: https://discourse.gohugo.io/t/how-to-get-a-specific-translation/32433/5

I've tried a few of those, but it doesn't work. The most promising seems to be `{{ $p := index (where .Page.AllTranslations "Language.Lang" "en-US") 0 }}` with `{{ $p.RelPermalink }}` but that doesn't work.

**Comment by elstoc** [comment]
I'm pretty sure I've fixed this on the website (we'll probably have to do something else for the pdf/epub so we should leave the issue open).

See https://darktable-org.github.io/dtdocs/de/module-reference/utility-modules/darkroom/color-assessment/ and https://darktable-org.github.io/dtdocs/module-reference/utility-modules/darkroom/color-assessment/

**Comment by lebmich** [comment]
A quick test shows that it seems to work. I will do more in-depth testing this evening.
Thank you so much.

**Comment by paperdigits** [comment]
Please reopen this issue if there is a problem, but it looks fixed to me.
