### ISSUE TITLE
lut 3D needs thorough documentation and mentions about possible movement in the pipeline

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/dtdocs#340]
Since https://github.com/darktable-org/darktable/pull/9914 got merged I REALLY think lut 3D needs more documentation about whys of LUTs and about placement of module depending on LUT use/intent. Sure, there are bunch of free LUTs that expect already done image, just to add some color shifts, but then there are pro-grade luts for grading films that expect eg film cLOG input (which looks like RAW but with adjusted exposure)... Users need to be informed about those intricacies imo.

This needs to be documented ideally by someone who knows ins&outs of various luts, not just display refered ones.

**Comment by phweyland** [comment]
If I'm the author of the module I'm not a frequent user.

There are some points to not forget:
- the module clips the input into [0,1]. There is no output outside [0,1].
- a LUT is always created in relation with specific input and output color spaces (or raw data).
- a LUT has no flexibility. You can just play with the opacity of the mask to control the effect.
-- between colorin and colorout the color space can be chosen and lut3d assumes that input and output color spaces are the same (as coded so far).
-- outside colorin and colorout lut3d inputs the current pipeline color space data and outputs the result without color space conversion.

So for dt, I see 2 main usages:
- color grading, film look,... working on linear or gamma color space, one of the list provided by the module. Of course we can add some others if necessary. The output color space is the same as the input one. Again, if necessary we could code the possibility of having 2 different color spaces.
-- the best place is after filmic and before colorout. If the user knows that the LUT works on the same color space as the pipeline one after colorout (it should be gamma sRGB but I'm not sure) he can move lut3d after colorout.
-- otherwise the result can still be OK for the user but probably not the advertised one.
- camera log (F-log, S-log3, ...). This kind of LUT should be able to translate the camera log raw data into a color space that dt understands.
-- I don't see why this could not work but having no file work with I've never verified this option.
-- the module should be placed between demosaic and colorin.

There are probably a lot of other types of LUT used in the cinema industry...
There are maybe other rules to prepare properly the image for color grading...

**Comment by elstoc** [comment]
Can this be closed now?

**Comment by phweyland** [comment]
> Can this be closed now?

I've added some info into dtdocs some time ago. Of course that doesn't exhaust the subject.
I would close it.

**Comment by elstoc** [comment]
Ok thanks.
