### ISSUE TITLE
Re-write all performance related settings

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/dtdocs#449]
@elstoc (and all people interested in the docs) this is somewhat demanding, first some general ideas

1. Should we keep the 32bit section at all?
2. I would write a section about "tiling - what is the relevance of it" both for cpu and gpu
3. A general introduction about the idea of "resourcelevel". This would include
   a) scenarios in which to use what level
   b) hints for the "nerds" about what the fractions mean. I personally think this part should be in the section we now use for memory and stuff like that. Maybe even call that "Nerds tuning"?
4. The "opencl tuning mode" should
   a) describe the checking for available memory
   b) mention the memory transfer mode used for tiling. That also have a hint that switching that on might be good on some systems, not so good on others.
   c) mention the new per_device conf key that could be tuned
   d) the internals of the device conf key should also go to the "nerds section". Some descriptions of those global OpenCl settings seem to be at least pretty outdated and maybe even wrong.

What approach would you prefer? Would you want me to write all docs as plain ascii and you modify the git repo? Or some pr's - (as i don't generate the docs myself and rely on the auto generated they might have errors you need to fix later) ?

**Comment by elstoc** [comment]
I'm fine with most of your suggestions, though I'd prefer to keep the manual as a fairly formally-styled document so we'll find some other term than "nerds tuning" :)

With the new documentation, it's pretty easy to run a copy of the website from a local repo if you need to test so PRs are fine (see the README and https://darktable-org.github.io/dtdocs/en/special-topics/contributing/). Perhaps propose something rough to start out with, either as a PR or a separate document, describing what you intend in more detail. There's been so much going on with these perf settings recently I don't have the first clue how they work, so perhaps a good starter would be a basic summary of what's changed since v3.8.

Whatever you propose will always go through a copy-edit from me either as part of your PR or shortly after it's merged. I'm happy to adapt to whatever way of working would be easier for you.

**Comment by elstoc** [comment]
Looks good for a first draft. Will probably make more sense once I see the geeks-eye-view as well :)

**Comment by jenshannoschwalm** [comment]
Just a note, I am currently investigating a rather obscure opencl problem (sometimes leading to hanging dt) so documentation is unfortunately delayed until that bug is resolved...

**Comment by jenshannoschwalm** [comment]
Ok, the bug was not a bug but an installation problem on my side mismatching kernel & nvidia stuff.

Here is another version of the file, this time i added technical information about resourcelevel setting. Are you ok this way?
[mem-management.odt](https://github.com/darktable-org/dtdocs/files/8788092/mem-management.odt)

**Comment by jenshannoschwalm** [comment]
Here is
1. An updated version of
[mem-management.odt](https://github.com/darktable-org/dtdocs/files/8799825/mem-management.odt)
2. A suggestion for technical details about opencl as
[performance.md](https://github.com/darktable-org/dtdocs/files/8799833/performance.md)
