### ISSUE TITLE
ETTR clarification

### ISSUE THREAD

**Issue by solitone** [darktable-org/dtdocs#532]
The [take a well-exposed photograph](https://docs.darktable.org/usermanual/4.0/en/overview/workflow/process/#take-a-well-exposed-photograph) section of the manual (v. 4.0) states that:

_Where possible, you are advised to use **exposure to-the-right (ETTR)** techniques to maximize the amount of data available for processing. As a general rule of thumb, it is safe to **under-expose** all images by 0.5 to 1 EV (by reducing the ISO sensitivity if possible) even if the in-camera preview looks darker than expected (the preview is not the raw data)._

The two points seem contradictory to someone inexperienced like me. ETTR would imply over-exposure. Is the manual suggesting to over- or under-expose?

Looking at the `exposure module` and the default `compensate camera exposure (-0.3 EV)` selection, I think the manual would suggest to over-expose, but the way is written is not completely clear to me.

I have been told that with high-dynamic range scenes, ETTR would mean under-exposure, to avoid clipping. I would suggest to specify this detail in the sentence above, though, so that even non experts like me have a more immediate understanding of it.

**Comment by elstoc** [comment]
ETTR means "expose so that the histogram just touches the right-hand-side but does not clip". One way that can achieve this is to let your camera calculate the correct exposure and then compensate down (dial in an in-camera exposure compensation) by 0.5 to 1EV. So the "under-exposure" is talking about "relative to what the camera automatically does".

ETTR usually results in darker images because in order to protect the highlights we have to stop them clipping. I don't see these points as contradictory and you should not expect to get an immediate understanding of ETTR from the user manual, since it's a guide to darktable and not to ETTR techniques.

Perhaps you could suggest some alternative wording for us to consider?

**Comment by solitone** [comment]
I'm just starting to learn all this, so I'm not in a good position to suggest a better wording. Perhaps I would just remove the second part of the sentence, leaving it simply like this:

_Where possible, you are advised to use exposure to-the-right (ETTR) techniques to maximize the amount of data available for processing._

The suggestion to under-expose by 0.5-1.0 EV seems pretty dependent on the metering of the camera. Plus, there are instances where you need to over-expose in order to ETTR, like the example discussed in the [Wikipedia page](https://en.wikipedia.org/wiki/Exposing_to_the_right) linked in the manual:

- [Picture 1](https://en.wikipedia.org/wiki/Exposing_to_the_right#/media/File:Histogram-Normal.png) of the example
- [Picture 2](https://en.wikipedia.org/wiki/Exposing_to_the_right#/media/File:Histogram-ETTR.png) of the example

But it's just my thought, I might well be wrong!

BTW, thanks for such an amazing manual. After using Silkypix, OM Workspace, iMovie and other commercial software, I've finally found something where I can learn something.

**Comment by paperdigits** [comment]
I actually think the following on Wikipedia is very poorly worded

> ETTR images requiring increased exposure may appear to be overexposed (too bright) when taken and must be correctly processed (normalized) to produce a photograph as envisaged. Care must be taken to avoid clipping within any colour channel, other than acceptable areas such as specular highlights

As this seems to refer to some specific type of scene. For instance, if you have a high key scene, the. ETTR might actually be underexposure.

The point being that don't let your histogram slide off the right hand side when metering in camera. Kiss the histogram to the right edge, and you've done ETTR.

**Comment by pilian** [comment]
Most Internet sources explain that ETTR means an over exposure.
For example wikipedia
or
https://photographylife.com/exposing-to-the-right-explained
`The basis of ETTR is simple: optimize your exposure, and get the highest-quality image possible. Most people expose a scene so that the image looks how they want — and, at face value, this makes sense. Optimum exposure is different, though. Instead of exposing the scene “correctly”, it is better to expose a scene to be as bright as possible, without blowing out the scene’s highlights and losing all of that data. Then, in post-processing, you darken the image so that it looks how you want.`

Exposing to the right means always to shift the histogram to the right. This results always in a brighter image.

The darktable manual suggests to under-expose the image with the camera. That is exposure to the LEFT, not to the RIGHT.

If the darktable suggestion is correct, then please dont refer to ETTR.

**Comment by elstoc** [comment]
No, you're misunderstanding. ETTR is about ensuring the data is not clipped. It doesn't "always result in a brighter image" and it doesn't mean "always shifting the histogram to the right". It means exposing in such a way that the brightest part of the image isn't blown out.

For low dynamic range images (e.g. a light grey object on a mid grey background) this might mean increasing exposure to capture more light. However, this is not true for scenes that exceed the dynamic range of the camera. For example, if I take an image in daylight that has some small bright highlights the camera will usually expose in such a way as to blow those highlights, while keeping the rest of the image "well exposed" (grey on average). In this case I want to dial in some negative exposure compensation (under-expose compared to what the camera wants me to do).

The suggestion to under-expose by 0.5-1.0 EV is basically saying that in most cases (for most cameras) in a high-dynamic-range scene this will stop the highlights being blown. This is "safe" for most modern cameras because modern cameras capture shadow details well and they can normally be restored in darktable. Blown highlights can only ever be reconstructed using guess-work and adjacent pixels because the data is lost.

**Comment by elstoc** [comment]
I've added some additional wording (https://github.com/darktable-org/dtdocs/commit/2a10ca38c7abaeffaf380f7255b8f9f271368500) that might clarify the intent of this section.

**Comment by pilian** [comment]
I'm no professional photographer and maybe I'm misunderstanding, but I have searched many websites with photo themes.
The main suggestion is "Expose to the right and develop to the dark"
The only site I found with the suggestion to darken the image of the camera is the darktable manual.
That's strange.

**Comment by gi-man** [comment]
> If the darktable suggestion is correct, then please dont refer to ETTR.

darktable is correct and it is ETTR but this is relative to the camera sensor capability and **not** to the histogram the camera displays. You want the maximum amount of energy to reach the sensor (energy = amount of light (lens aperture) and duration (shutter speed)) for a given iso. But you do not want to be so high that it exceeds the capability of the sensor (clipped highlights). Therefore capture the image with as much possible exposure without clipping. In some cameras you need to adjust the camera settings to show a camera histogram with underexposure to archive this.

**Comment by paperdigits** [comment]
This seems as clear as it is going to be. Closing.
